name: Flutter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  cirrusci/flutter
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo ${HOME}/sdks/flutter/bin/flutter pub get
    - name: Run tests
      run: sudo flutter test
