name: Flutter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  cirrusci/flutter
    
    steps:
    - uses: actions/checkout@v1
    - name: sudo
    - run: apt install sudo
    - name: Install dependencies
      run: sudo -u root flutter pub get
    - name: Run tests
      run: sudo -u root flutter test
