name: CI

on:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  cirrusci/flutter
    
    steps:
    - uses: actions/checkout@v1    
    - name: Creates .env file
      run: sudo cp .env.prod .env
    - name: Install dependencies
      run: sudo /home/cirrus/sdks/flutter/bin/flutter pub get    
    - name: Run tests
      run: sudo /home/cirrus/sdks/flutter/bin/flutter test
    - name: print secret
      run: echo ${{ secrets.LARGE_SECRET_PASSPHRASE }}
    - name: Decrypt large secret
      run: sudo ./.github/scripts/decrypt_secret.sh
      env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
    - name: Build App Bundle
      run: sudo /home/cirrus/sdks/flutter/bin/flutter build appbundle
