name: CBPQ Develop

on:
  push:
    branches: 
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  cirrusci/flutter
    
    steps:
    - uses: actions/checkout@v1    
    - name: Install dependencies
      run: sudo /home/cirrus/sdks/flutter/bin/flutter pub get
    - name: Run tests
      run: sudo /home/cirrus/sdks/flutter/bin/flutter test
    - name: Creantes .env file
      run: sudo cp .env.prod .env
    - name: Decrypt large secret
      run: |
        secrets/decrypt_secret.sh
        mv key.jks android/app
      env:
          LARGE_SECRET_PASSPHRASE: $
    - name: Build App Bundle
      run: sudo /home/cirrus/sdks/flutter/bin/flutter build appbundle
